// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $greet_agendacsr from "./routes/greet/agendacsr.tsx";
import * as $greet_agendassr from "./routes/greet/agendassr.tsx";
import * as $index from "./routes/index.tsx";
import * as $layout from "./routes/layout.tsx";
import * as $AgendaManager from "./islands/AgendaManager.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/greet/agendacsr.tsx": $greet_agendacsr,
    "./routes/greet/agendassr.tsx": $greet_agendassr,
    "./routes/index.tsx": $index,
    "./routes/layout.tsx": $layout,
  },
  islands: {
    "./islands/AgendaManager.tsx": $AgendaManager,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
